### ISSUE TITLE
Amazing Idea

### ISSUE THREAD

**Issue by taureau75** [anders94/order-matching-engine#9]
I don't have an issue. I just wanted to say this is an amazing idea. 

I run a layer 2 orderbook exchange: https://trade.zigzag.exchange. 

We're going to be using this code in our backend. We will happily contribute code to extend the functionality.  

Order cancels, stop orders, expirations. These are all ways we would like to contribute to and extend the project.

**Comment by anders94** [comment]
Thanks! Best of luck with it.
